web:
  build: .
  command: php -S 0.0.0.0:8000 -t /app
  links:
    - db
  ports:
    - "8080:8000"
  volumes:
    - ./app:/app/maestro/apps
db:
  image: mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp
